project:
  type: website

website:
  title: "DSAN-5600 Project - Yifan Hu"
  sidebar:
    style: "docked"
    contents: 
      - href: index.qmd
        text: Introduction
      - href: Data-Sources.qmd
        text: Data Sources
      - href: Data-Visualization.qmd
        text: Data Visualization
      - href: Exploratory-Data-Analysis.qmd
        text: Exploratory Data Analysis
      - href: ARMA-ARIMA-SARIMA.qmd
        text: ARMA/ARIMA/SARIMA Models
      - href: ARIMAX-SARIMAX-VAR.qmd
        text: ARIMAX/SARIMAX/VAR Models 
      - href: Financial-Models.qmd
        text: Financial Time Series Models
      - href: Deep-Learning.qmd
        text: Deep Learning for TS
      - href: Conclusion.qmd
        text: Conclusion
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/hyf112/DSAN-5600-Project.git

format:
  html:
    theme: 
      - lux
      - custom.scss
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: false
    code-fold: true
    code-copy: true
    code-tools: true
    code-overflow: wrap

editor: visual



